<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
accepts the
<EntityLink name="object" />. The
<EntityLink name="target" />
property can be used in certain circumstances to indicate the context into which the
<EntityLink name="object" />
has been accepted.
