<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates the accuracy of position coordinates on a
<EntityLink name="Place" />
objects. Expressed in properties of percentage. e.g. "94.0" means "94.0% accurate".
