<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates the accuracy of position coordinates on a
<EntityLink name="Place" />
objects. Expressed in properties of percentage. e.g. "94.0" means "94.0% accurate".

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="name"
	/>": "Liu Gu Lu Cun, Pingdu, Qingdao, Shandong, China",
  "<EntityLink
		name="type"
	/>": "Place",
  "<EntityLink name="latitude" />": 36.75,
  "<EntityLink
		name="longitude"
	/>": 119.7667,
  "<EntityLink name="accuracy" />": 94.5
{'}'}
			</pre>
