<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

An
<EntityLink name="Activity" />
is a subtype of
<EntityLink name="Object" />
that describes some form of action that may happen, is currently happening, or has already happened.
The
<EntityLink name="Activity" />
type itself serves as an abstract base type for all types of activities. It is important to note
that the
<EntityLink name="Activity" />
type itself does not carry any specific semantics about the kind of action being taken.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Activity",
  "<EntityLink name="summary" />": "Sally did something to a note",
  "<EntityLink
		name="actor"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally"
  {'}'},
  "<EntityLink name="object" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Note",
    "<EntityLink name="name" />": "A Note"
  {'}'}
{'}'}
			</pre>
