<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Describes one or more entities that either performed or are expected to perform the activity. Any
single activity can have multiple
<EntityLink name="actor" />s. The
<EntityLink name="actor" />
MAY be specified using an indirect
<EntityLink name="Link" />.
