<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Describes one or more entities that either performed or are expected to perform the activity. Any
single activity can have multiple
<EntityLink name="actor" />s. The
<EntityLink name="actor" />
MAY be specified using an indirect
<EntityLink name="Link" />.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally offered the Foo object",
  "<EntityLink name="type" />": "Offer",
  "<EntityLink
		name="actor"
	/>": "http://sally.example.org",
  "<EntityLink
		name="object"
	/>": "http://example.org/foo"
{'}'}
			</pre>

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally offered the Foo object",
  "<EntityLink name="type" />": "Offer",
  "<EntityLink
		name="actor"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="id"
	/>": "http://sally.example.org",
    "<EntityLink name="summary" />": "Sally"
  {'}'},
  "<EntityLink
		name="object"
	/>": "http://example.org/foo"
{'}'}
			</pre>

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally and Joe offered the Foo object",
  "<EntityLink name="type" />": "Offer",
  "<EntityLink
		name="actor"
	/>": [
    "http://joe.example.org",
    {'{'}
      "<EntityLink
		name="type"
	/>": "Person",
      "<EntityLink name="id" />": "http://sally.example.org",
      "<EntityLink
		name="name"
	/>": "Sally"
    {'}'}
  ],
  "<EntityLink name="object" />": "http://example.org/foo"
{'}'}
			</pre>
