<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
has added the
<EntityLink name="object" />
to the
<EntityLink name="target" />. If the
<EntityLink name="target" />
property is not explicitly specified, the target would need to be determined implicitly by context.
The
<EntityLink name="origin" />
can be used to identify the context from which the
<EntityLink name="object" />
originated.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally added an object",
  "<EntityLink name="type" />": "Add",
  "<EntityLink
		name="actor"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally"
  {'}'},
  "<EntityLink name="object" />": "http://example.org/abc"
{'}'}
			</pre>

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally added a picture of her cat to her cat picture collection",
  "<EntityLink
		name="type"
	/>": "Add",
  "<EntityLink name="actor" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Person",
    "<EntityLink name="name" />": "Sally"
  {'}'},
  "<EntityLink
		name="object"
	/>": {'{'}
    "<EntityLink name="type" />": "Image",
    "<EntityLink
		name="name"
	/>": "A picture of my cat",
    "<EntityLink
		name="url"
	/>": "http://example.org/img/cat.png"
  {'}'},
  "<EntityLink
		name="origin"
	/>": {'{'}
    "<EntityLink name="type" />": "Collection",
    "<EntityLink
		name="name"
	/>": "Camera Roll"
  {'}'},
  "<EntityLink name="target" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Collection",
    "<EntityLink name="name" />": "My Cat Pictures"
  {'}'}
{'}'}
			</pre>
