<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
has added the
<EntityLink name="object" />
to the
<EntityLink name="target" />. If the
<EntityLink name="target" />
property is not explicitly specified, the target would need to be determined implicitly by context.
The
<EntityLink name="origin" />
can be used to identify the context from which the
<EntityLink name="object" />
originated.
