<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates the altitude of a place. The measurement units is indicated using the
<EntityLink name="units" />
property. If
<EntityLink name="units" />
is not specified, the default is assumed to be "m" indicating meters.
