<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is calling the
<EntityLink name="target" />'s attention the
<EntityLink name="object" />. The
<EntityLink name="origin" />
typically has no defined meaning.
