<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies an inclusive option for a
<EntityLink name="Question" />. Use of
<EntityLink name="anyOf" />
implies that the
<EntityLink name="Question" />
can have multiple answers. To indicate that a
<EntityLink name="Question" />
can have only one answer, use
<EntityLink name="oneOf" />.
