<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

An
<EntityLink name="IntransitiveActivity" />
that indicates that the
<EntityLink name="actor" />
has arrived at the
<EntityLink name="location" />. The
<EntityLink name="origin" />
can be used to identify the context from which the
<EntityLink name="actor" />
originated. The
<EntityLink name="target" />
typically has no defined meaning.
