<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

An
<EntityLink name="IntransitiveActivity" />
that indicates that the
<EntityLink name="actor" />
has arrived at the
<EntityLink name="location" />. The
<EntityLink name="origin" />
can be used to identify the context from which the
<EntityLink name="actor" />
originated. The
<EntityLink name="target" />
typically has no defined meaning.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally arrived at work",
  "<EntityLink name="type" />": "Arrive",
  "<EntityLink
		name="actor"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally"
  {'}'},
  "<EntityLink name="location" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Place",
    "<EntityLink name="name" />": "Work"
  {'}'},
  "<EntityLink
		name="origin"
	/>": {'{'}
    "<EntityLink name="type" />": "Place",
    "<EntityLink
		name="name"
	/>": "Home"
  {'}'}
{'}'}
			</pre>
