<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies a resource attached or related to an object that potentially requires special handling.
The intent is to provide a model that is at least semantically similar to attachments in email.
