<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies a resource attached or related to an object that potentially requires special handling.
The intent is to provide a model that is at least semantically similar to attachments in email.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Note",
  "<EntityLink name="name" />": "Have you seen my cat?",
  "<EntityLink
		name="attachment"
	/>": [
    {'{'}
      "<EntityLink name="type" />": "Image",
      "<EntityLink
		name="content"
	/>": "This is what he looks like.",
      "<EntityLink
		name="url"
	/>": "http://example.org/cat.jpeg"
    {'}'}
  ]
{'}'}
			</pre>
