<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies one or more entities to which this object is attributed. The attributed entities might
not be Actors. For instance, an object might be attributed to the completion of another activity.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Image",
  "<EntityLink name="name" />": "My cat taking a nap",
  "<EntityLink
		name="url"
	/>": "http://example.org/cat.jpeg",
  "<EntityLink
		name="attributedTo"
	/>": [
    {'{'}
      "<EntityLink name="type" />": "Person",
      "<EntityLink
		name="name"
	/>": "Sally"
    {'}'}
  ]
{'}'}
			</pre>

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Image",
  "<EntityLink name="name" />": "My cat taking a nap",
  "<EntityLink
		name="url"
	/>": "http://example.org/cat.jpeg",
  "<EntityLink
		name="attributedTo"
	/>": [
    "http://joe.example.org",
    {'{'}
      "<EntityLink
		name="type"
	/>": "Person",
      "<EntityLink name="name" />": "Sally"
    {'}'}
  ]
{'}'}
			</pre>
