<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies one or more entities to which this object is attributed. The attributed entities might
not be Actors. For instance, an object might be attributed to the completion of another activity.
