<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is blocking the
<EntityLink name="object" />. Blocking is a stronger form of
<EntityLink name="Ignore" />. The typical use is to support social systems that allow one user to
block activities or content of other users. The
<EntityLink name="target" />
and
<EntityLink name="origin" />
typically have no defined meaning.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally blocked Joe",
  "<EntityLink name="type" />": "Block",
  "<EntityLink
		name="actor"
	/>": "http://sally.example.org",
  "<EntityLink
		name="object"
	/>": "http://joe.example.org"
{'}'}
			</pre>
