<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies an Object that is part of the private primary audience of this Object.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally offered a post to John",
  "<EntityLink name="type" />": "Offer",
  "<EntityLink
		name="actor"
	/>": "http://sally.example.org",
  "<EntityLink
		name="object"
	/>": "http://example.org/posts/1",
  "<EntityLink
		name="target"
	/>": "http://john.example.org",
  "<EntityLink
		name="bto"
	/>": [
    "http://joe.example.org"
  ]
{'}'}
			</pre>
