<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that a question has been closed, and answers are no longer accepted.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Question",
  "<EntityLink name="name" />": "What is the answer?",
  "<EntityLink
		name="closed"
	/>": "2016-05-10T00:00:00Z"
{'}'}
			</pre>
