<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Used to represent distinct subsets of items from a
<EntityLink name="Collection" />. Refer to the
<a href="https://www.w3.org/TR/activitystreams-core/#dfn-collectionpage">Activity Streams 2.0 Core</a>
for a complete description of the
<EntityLink name="CollectionPage" />
object.
