<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Used to represent distinct subsets of items from a
<EntityLink name="Collection" />. Refer to the
<a href="https://www.w3.org/TR/activitystreams-core/#dfn-collectionpage">Activity Streams 2.0 Core</a>
for a complete description of the
<EntityLink name="CollectionPage" />
object.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Page 1 of Sally's notes",
  "<EntityLink name="type" />": "CollectionPage",
  "<EntityLink
		name="id"
	/>": "http://example.org/foo?page=1",
  "<EntityLink
		name="partOf"
	/>": "http://example.org/foo",
  "<EntityLink name="items" />": [
    {'{'}
      "<EntityLink
		name="type"
	/>": "Note",
      "<EntityLink
		name="name"
	/>": "A Simple Note"
    {'}'},
    {'{'}
      "<EntityLink
		name="type"
	/>": "Note",
      "<EntityLink name="name" />": "Another Simple Note"
    {'}'}
  ]
{'}'}
			</pre>
