<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A
<EntityLink name="Collection" />
is a subtype of
<EntityLink name="Object" />
that represents ordered or unordered sets of
<EntityLink name="Object" />
or
<EntityLink name="Link" />
instances. Refer to the
<a href="https://www.w3.org/TR/activitystreams-core/#collection">Activity Streams 2.0 Core</a>
specification for a complete description of the
<EntityLink name="Collection" />
type.
