<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

The content or textual representation of the
<EntityLink name="Object" />
encoded as a JSON string. By default, the value of
<EntityLink name="content" />
is HTML. The
<EntityLink name="mediaType" />
property can be used in the object to indicate a different content type. The content MAY be
expressed using multiple language-tagged values.
