<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies the context within which the object exists or an activity was performed. The notion of
"context" used is intentionally vague. The intended function is to serve as a means of grouping
objects and activities that share a common originating context or purpose. An example could be all
activities relating to a common project or event.
