<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
has deleted the
<EntityLink name="object" />. If specified, the
<EntityLink name="origin" />
indicates the context from which the
<EntityLink name="object" />
was deleted.
