<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Tombstone" />
object, the
<EntityLink name="deleted" />
property is a timestamp for when the object was deleted.
