<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Tombstone" />
object, the
<EntityLink name="deleted" />
property is a timestamp for when the object was deleted.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "This image has been deleted",
  "<EntityLink name="type" />": "Tombstone",
  "<EntityLink
		name="deleted"
	/>": "2016-05-03T00:00:00Z"
{'}'}
			</pre>
