<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Profile" />
object, the
<EntityLink name="describes" />
property identifies the object described by the
<EntityLink name="Profile" />.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally's profile",
  "<EntityLink name="type" />": "Profile",
  "<EntityLink
		name="describes"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally"
  {'}'},
  "<EntityLink name="url" />": "http://sally.example.org"
{'}'}
			</pre>
