<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Profile" />
object, the
<EntityLink name="describes" />
property identifies the object described by the
<EntityLink name="Profile" />.
