<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Represents a document of any kind.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Document",
  "<EntityLink name="name" />": "4Q Sales Forecast",
  "<EntityLink
		name="url"
	/>": "http://example.org/4q-sales-forecast.pdf"
{'}'}
			</pre>
