<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

When the object describes a time-bound resource, such as an audio or video, a meeting, etc, the
<EntityLink name="duration" />
property indicates the object's approximate duration. The value MUST be expressed as an
`xsd:duration` as defined by [
<a href="https://www.w3.org/TR/activitystreams-vocabulary/#bib-xmlschema11-2">xmlschema11-2</a>],
section 3.3.6 (e.g. a period of 5 seconds is represented as "PT5S").

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Video",
  "<EntityLink name="name" />": "Birds Flying",
  "<EntityLink
		name="url"
	/>": "http://example.org/video.mkv",
  "<EntityLink name="duration" />": "PT2H"
{'}'}
			</pre>
