<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

The date and time describing the actual or expected ending time of the object. When used with an
<EntityLink name="Activity" />
object, for instance, the
<EntityLink name="endTime" />
property specifies the moment the activity concluded or is expected to conclude.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Event",
  "<EntityLink name="name" />": "Going-Away Party for Jim",
  "<EntityLink
		name="startTime"
	/>": "2014-12-31T23:00:00-08:00",
  "<EntityLink
		name="endTime"
	/>": "2015-01-01T06:00:00-08:00"
{'}'}
			</pre>
