<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Represents any kind of event.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Event",
  "<EntityLink name="name" />": "Going-Away Party for Jim",
  "<EntityLink
		name="startTime"
	/>": "2014-12-31T23:00:00-08:00",
  "<EntityLink
		name="endTime"
	/>": "2015-01-01T06:00:00-08:00"
{'}'}
			</pre>
