<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is "flagging" the
<EntityLink name="object" />. Flagging is defined in the sense common to many social platforms as
reporting content as being inappropriate for any number of reasons.
