<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is "following" the
<EntityLink name="object" />. Following is defined in the sense typically used within Social systems
in which the actor is interested in any activity performed by or on the object. The
<EntityLink name="target" />
and
<EntityLink name="origin" />
typically have no defined meaning.
