<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is "following" the
<EntityLink name="object" />. Following is defined in the sense typically used within Social systems
in which the actor is interested in any activity performed by or on the object. The
<EntityLink name="target" />
and
<EntityLink name="origin" />
typically have no defined meaning.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally followed John",
  "<EntityLink name="type" />": "Follow",
  "<EntityLink
		name="actor"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally"
  {'}'},
  "<EntityLink name="object" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Person",
    "<EntityLink name="name" />": "John"
  {'}'}
{'}'}
			</pre>
