<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Tombstone" />
object, the
<EntityLink name="formerType" />
property identifies the type of the object that was deleted.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "This image has been deleted",
  "<EntityLink name="type" />": "Tombstone",
  "<EntityLink
		name="formerType"
	/>": "Image",
  "<EntityLink name="url" />": "http://example.org/image/2"
{'}'}
			</pre>
