<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Tombstone" />
object, the
<EntityLink name="formerType" />
property identifies the type of the object that was deleted.
