<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies the entity (e.g. an application) that generated the object.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "A simple note",
  "<EntityLink name="type" />": "Note",
  "<EntityLink
		name="content"
	/>": "This is all there is.",
  "<EntityLink name="generator" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Application",
    "<EntityLink name="name" />": "Exampletron 3000"
  {'}'}
{'}'}
			</pre>
