<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Hints as to the language used by the target resource. Value MUST be a [<a
	href="https://www.w3.org/TR/activitystreams-vocabulary/#bib-BCP47"
>BCP47</a>] Language-Tag.
