<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates an entity that describes an icon for this object. The image should have an aspect ratio of
one (horizontal) to one (vertical) and should be suitable for presentation at a small size.
