<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Provides the globally unique identifier for an
<EntityLink name="Object" />
or
<EntityLink name="Link" />.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="name"
	/>": "Foo",
  "<EntityLink name="id" />": "http://example.org/foo"
{'}'}
			</pre>
