<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Provides the globally unique identifier for an
<EntityLink name="Object" />
or
<EntityLink name="Link" />.
