<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates an entity that describes an image for this object. Unlike the icon property, there are no
aspect ratio or display size limitations assumed.
