<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Instances of
<EntityLink name="IntransitiveActivity" />
are a subtype of
<EntityLink name="Activity" />
representing intransitive actions. The
<EntityLink name="object" />
property is therefore inappropriate for these activities.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Travel",
  "<EntityLink name="summary" />": "Sally went to work",
  "<EntityLink
		name="actor"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally"
  {'}'},
  "<EntityLink name="target" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Place",
    "<EntityLink name="name" />": "Work"
  {'}'}
{'}'}
			</pre>
