<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Instances of
<EntityLink name="IntransitiveActivity" />
are a subtype of
<EntityLink name="Activity" />
representing intransitive actions. The
<EntityLink name="object" />
property is therefore inappropriate for these activities.
