<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A specialization of
<EntityLink name="Offer" />
in which the
<EntityLink name="actor" />
is extending an invitation for the
<EntityLink name="object" />
to the
<EntityLink name="target" />.
