<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
likes, recommends or endorses the
<EntityLink name="object" />. The
<EntityLink name="target" />
and
<EntityLink name="origin" />
typically have no defined meaning.
