<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A
<EntityLink name="Link" />
is an indirect, qualified reference to a resource identified by a URL. The fundamental model for
links is established by [
<a href="https://www.w3.org/TR/activitystreams-vocabulary/#bib-RFC5988">RFC5988</a>]. Many of the
properties defined by the Activity Vocabulary allow values that are either instances of

<EntityLink name="Object" />
or
<EntityLink name="Link" />. When a
<EntityLink name="Link" />
is used, it establishes a
<a href="http://patterns.dataincubator.org/book/qualified-relation.html">qualified relation</a>
connecting the subject (the containing object) to the resource identified by the
<EntityLink name="href" />. Properties of the
<EntityLink name="Link" />
are properties of the reference as opposed to properties of the resource.
