<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

The longitude of a place
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Place",
  "<EntityLink name="name" />": "Fresno Area",
  "<EntityLink
		name="latitude"
	/>": 36.75,
  "<EntityLink name="longitude" />": 119.7667,
  "<EntityLink
		name="radius"
	/>": 15,
  "<EntityLink name="units" />": "miles"
{'}'}
			</pre>
