<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

When used on a
<EntityLink name="Link" />, identifies the MIME media type of the referenced resource. When used on
an
<EntityLink name="Object" />, identifies the MIME media type of the value of the
<EntityLink name="content" />
property. If not specified, the
<EntityLink name="content" />
property is assumed to contain text/html content.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Link",
  "<EntityLink name="href" />": "http://example.org/abc",
  "<EntityLink
		name="hreflang"
	/>": "en",
  "<EntityLink name="mediaType" />": "text/html",
  "<EntityLink
		name="name"
	/>": "Next"
{'}'}
			</pre>
