<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
has moved
<EntityLink name="object" />
from
<EntityLink name="origin" />
to
<EntityLink name="target" />. If the
<EntityLink name="origin" />
or
<EntityLink name="target" />
are not specified, either can be determined by context.
