<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
has moved
<EntityLink name="object" />
from
<EntityLink name="origin" />
to
<EntityLink name="target" />. If the
<EntityLink name="origin" />
or
<EntityLink name="target" />
are not specified, either can be determined by context.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally moved a post from List A to List B",
  "<EntityLink
		name="type"
	/>": "Move",
  "<EntityLink name="actor" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Person",
    "<EntityLink name="name" />": "Sally"
  {'}'},
  "<EntityLink
		name="object"
	/>": "http://example.org/posts/1",
  "<EntityLink name="target" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Collection",
    "<EntityLink name="name" />": "List B"
  {'}'},
  "<EntityLink
		name="origin"
	/>": {'{'}
    "<EntityLink name="type" />": "Collection",
    "<EntityLink
		name="name"
	/>": "List A"
  {'}'}
{'}'}
			</pre>
