<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A simple, human-readable, plain-text name for the object. HTML markup MUST NOT be included. The name
MAY be expressed using multiple language-tagged values.
