<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

In a paged
<EntityLink name="Collection" />, indicates the next page of items.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Page 2 of Sally's blog posts",
  "<EntityLink
		name="type"
	/>": "CollectionPage",
  "<EntityLink
		name="next"
	/>": "http://example.org/collection?page=2",
  "<EntityLink
		name="items"
	/>": [
    "http://example.org/posts/1",
    "http://example.org/posts/2",
    "http://example.org/posts/3"
  ]
{'}'}
			</pre>

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Page 2 of Sally's blog posts",
  "<EntityLink
		name="type"
	/>": "CollectionPage",
  "<EntityLink name="next" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Link",
    "<EntityLink name="name" />": "Next Page",
    "<EntityLink
		name="href"
	/>": "http://example.org/collection?page=2"
  {'}'},
  "<EntityLink
		name="items"
	/>": [
    "http://example.org/posts/1",
    "http://example.org/posts/2",
    "http://example.org/posts/3"
  ]
{'}'}
			</pre>
