<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

In a paged
<EntityLink name="Collection" />, indicates the next page of items.
