<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

When used within an
<EntityLink name="Activity" />, describes the direct object of the activity. For instance, in the
activity "John added a movie to his wishlist", the object of the activity is the movie added. When
used within a
<EntityLink name="Relationship" />
describes the entity to which the
<EntityLink name="subject" />
is related.
