<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Describes an object of any kind. The
<EntityLink name="Object" />
type serves as the base type for most of the other kinds of objects defined in the Activity
Vocabulary, including other Core types such as
<EntityLink name="Activity" />,
<EntityLink name="IntransitiveActivity" />,
<EntityLink name="Collection" />
and
<EntityLink name="OrderedCollection" />.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Object",
  "<EntityLink name="id" />": "http://www.test.example/object/1",
  "<EntityLink
		name="name"
	/>": "A Simple, non-specific object"
{'}'}
			</pre>
