<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

When used within an
<EntityLink name="Activity" />, describes the direct object of the activity. For instance, in the
activity "John added a movie to his wishlist", the object of the activity is the movie added. When
used within a
<EntityLink name="Relationship" />
describes the entity to which the
<EntityLink name="subject" />
is related.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally liked a post",
  "<EntityLink name="type" />": "Like",
  "<EntityLink
		name="actor"
	/>": "http://sally.example.org",
  "<EntityLink
		name="object"
	/>": "http://example.org/posts/1"
{'}'}
			</pre>

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Like",
  "<EntityLink name="actor" />": "http://sally.example.org",
  "<EntityLink
		name="object"
	/>": {'{'}
    "<EntityLink name="type" />": "Note",
    "<EntityLink
		name="content"
	/>": "A simple note"
  {'}'}
{'}'}
			</pre>

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally liked a note",
  "<EntityLink name="type" />": "Like",
  "<EntityLink
		name="actor"
	/>": "http://sally.example.org",
  "<EntityLink
		name="object"
	/>": [
    "http://example.org/posts/1",
    {'{'}
      "<EntityLink
		name="type"
	/>": "Note",
      "<EntityLink name="summary" />": "A simple note",
      "<EntityLink
		name="content"
	/>": "That is a tree."
    {'}'}
  ]
{'}'}
			</pre>
