<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is offering the
<EntityLink name="object" />. If specified, the
<EntityLink name="target" />
indicates the entity to which the
<EntityLink name="object" />
is being offered.
