<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies an exclusive option for a
<EntityLink name="Question" />. Use of
<EntityLink name="oneOf" />
implies that the
<EntityLink name="Question" />
can have only a single answer. To indicate that a
<EntityLink name="Question" />
can have multiple answers, use
<EntityLink name="anyOf" />.
