<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A subtype of
<EntityLink name="Collection" />
in which members of the logical collection are assumed to always be strictly ordered.
