<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Describes an indirect object of the activity from which the activity is directed. The precise
meaning of the origin is the object of the English preposition "from". For instance, in the activity
"John moved an item to List B from List A", the origin of the activity is "List A".
