<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Represents a Web Page.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Page",
  "<EntityLink name="name" />": "Omaha Weather Report",
  "<EntityLink
		name="url"
	/>": "http://example.org/weather-in-omaha.html"
{'}'}
			</pre>
