<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Represents an individual person.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Person",
  "<EntityLink name="name" />": "Sally Smith"
{'}'}
			</pre>
