<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Represents a logical or physical location. See
<a href="https://www.w3.org/TR/activitystreams-vocabulary/#places">5.3 Representing Places</a>
for additional information.
