<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

In a paged
<EntityLink name="Collection" />, identifies the previous page of items.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Page 1 of Sally's blog posts",
  "<EntityLink
		name="type"
	/>": "CollectionPage",
  "<EntityLink
		name="prev"
	/>": "http://example.org/collection?page=1",
  "<EntityLink
		name="items"
	/>": [
    "http://example.org/posts/1",
    "http://example.org/posts/2",
    "http://example.org/posts/3"
  ]
{'}'}
			</pre>

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Page 1 of Sally's blog posts",
  "<EntityLink
		name="type"
	/>": "CollectionPage",
  "<EntityLink name="prev" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Link",
    "<EntityLink name="name" />": "Previous Page",
    "<EntityLink
		name="href"
	/>": "http://example.org/collection?page=1"
  {'}'},
  "<EntityLink
		name="items"
	/>": [
    "http://example.org/posts/1",
    "http://example.org/posts/2",
    "http://example.org/posts/3"
  ]
{'}'}
			</pre>
