<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A
<EntityLink name="Profile" />
is a content object that describes another
<EntityLink name="Object" />, typically used to describe `Actor Type` objects. The
<EntityLink name="describes" />
property is used to reference the object being described by the profile.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="type"
	/>": "Profile",
  "<EntityLink name="summary" />": "Sally's Profile",
  "<EntityLink
		name="describes"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally Smith"
  {'}'}
{'}'}
			</pre>
