<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Represents a question being asked. Question objects are an extension of
<EntityLink name="IntransitiveActivity" />. That is, the
<EntityLink name="Question" />
object is an
<EntityLink name="Activity" />, but the direct object is the question itself and therefore it would
not contain an
<EntityLink name="object" />
property. Either of the
<EntityLink name="anyOf" />
and
<EntityLink name="oneOf" />
properties MAY be used to express possible answers, but a Question object MUST NOT have both
properties.
