<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

The radius from the given
<EntityLink name="latitude" />
and
<EntityLink name="longitude" />
for a
<EntityLink name="Place" />. The units is expressed by the
<EntityLink name="units" />
property. If
<EntityLink name="units" />
is not specified, the default is assumed to be "m" indicating "meters".
