<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A link relation associated with a
<EntityLink name="Link" />. The value MUST conform to both the [<a
	href="https://www.w3.org/TR/activitystreams-vocabulary/#bib-HTML5"
>HTML5</a>] and [<a
	href="https://www.w3.org/TR/activitystreams-vocabulary/#bib-RFC5988"
>RFC5988</a>] "link relation" definitions. In the [<a
	href="https://www.w3.org/TR/activitystreams-vocabulary/#bib-HTML5"
>HTML5</a>], any string not containing the "space" U+0020, "tab" (U+0009), "LF" (U+000A), "FF"
(U+000C), "CR" (U+000D) or "," (U+002C) characters can be used as a valid link relation.
