<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Describes a relationship between two individuals. The
<EntityLink name="subject" />
and
<EntityLink name="object" />
properties are used to identify the connected individuals.
<a href="https://www.w3.org/TR/activitystreams-vocabulary/#connections">See 5.2 Representing
	Relationships Between Entities</a>
for additional information.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally is an acquaintance of John",
  "<EntityLink
		name="type"
	/>": "Relationship",
  "<EntityLink name="subject" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Person",
    "<EntityLink name="name" />": "Sally"
  {'}'},
  "<EntityLink
		name="relationship"
	/>": "http://purl.org/vocab/relationship/acquaintanceOf",
  "<EntityLink
		name="object"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "John"
  {'}'}
{'}'}
			</pre>
