<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Relationship" />
object, the
<EntityLink name="relationship" />
property identifies the kind of relationship that exists between
<EntityLink name="subject" />
and
<EntityLink name="object" />.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally is an acquaintance of John's",
  "<EntityLink
		name="type"
	/>": "Relationship",
  "<EntityLink name="subject" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Person",
    "<EntityLink name="name" />": "Sally"
  {'}'},
  "<EntityLink
		name="relationship"
	/>": "http://purl.org/vocab/relationship/acquaintanceOf",
  "<EntityLink
		name="object"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "John"
  {'}'}
{'}'}
			</pre>
