<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Describes a relationship between two individuals. The
<EntityLink name="subject" />
and
<EntityLink name="object" />
properties are used to identify the connected individuals.
<a href="https://www.w3.org/TR/activitystreams-vocabulary/#connections">See 5.2 Representing
	Relationships Between Entities</a>
for additional information.
