<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Relationship" />
object, the
<EntityLink name="relationship" />
property identifies the kind of relationship that exists between
<EntityLink name="subject" />
and
<EntityLink name="object" />.
