<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies a
<EntityLink name="Collection" />
containing objects considered to be responses to this object.
