<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

The date and time describing the actual or expected starting time of the object. When used with an
<EntityLink name="Activity" />
object, for instance, the
<EntityLink name="startTime" />
property specifies the moment the activity began or is scheduled to begin.
