<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A non-negative integer value identifying the relative position within the logical view of a strictly
ordered collection.
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Page 1 of Sally's notes",
  "<EntityLink
		name="type"
	/>": "OrderedCollectionPage",
  "<EntityLink name="startIndex" />": 0,
  "<EntityLink
		name="orderedItems"
	/>": [
    {'{'}
      "<EntityLink name="type" />": "Note",
      "<EntityLink
		name="name"
	/>": "Density of Water"
    {'}'},
    {'{'}
      "<EntityLink
		name="type"
	/>": "Note",
      "<EntityLink name="name" />": "Air Mattress Idea"
    {'}'}
  ]
{'}'}
			</pre>
