<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A non-negative integer value identifying the relative position within the logical view of a strictly
ordered collection.
