<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Relationship" />
object, the
<EntityLink name="subject" />
property identifies one of the connected individuals. For instance, for a
<EntityLink name="Relationship" />
object describing "John is related to Sally",
<EntityLink name="subject" />
would refer to John.
