<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A natural language summarization of the object encoded as HTML. Multiple language tagged summaries
MAY be provided.
