<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Describes the indirect object, or target, of the activity. The precise meaning of the target is
largely dependent on the type of action being described but will often be the object of the English
preposition "to". For instance, in the activity "John added a movie to his wishlist", the target of
the activity is John's wishlist. An activity can have more than one target.
