<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A specialization of
<EntityLink name="Reject" />
in which the rejection is considered tentative.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally tentatively rejected an invitation to a party",
  "<EntityLink
		name="type"
	/>": "TentativeReject",
  "<EntityLink name="actor" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Person",
    "<EntityLink name="name" />": "Sally"
  {'}'},
  "<EntityLink
		name="object"
	/>": {'{'}
    "<EntityLink name="type" />": "Invite",
    "<EntityLink
		name="actor"
	/>": "http://john.example.org",
    "<EntityLink name="object" />": {'{'}
      "<EntityLink
		name="type"
	/>": "Event",
      "<EntityLink
		name="name"
	/>": "Going-Away Party for Jim"
    {'}'}
  {'}'}
{'}'}
			</pre>
