<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A specialization of
<EntityLink name="Accept" />
indicating that the acceptance is tentative.
