<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A
<EntityLink name="Tombstone" />
represents a content object that has been deleted. It can be used in
<EntityLink name="Collection" />s to signify that there used to be an object at this position, but
it has been deleted.
