<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

A non-negative integer specifying the total number of objects contained by the logical view of the
collection. This number might not reflect the actual number of items serialized within the
<EntityLink name="Collection" />
object instance.
