<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is traveling to
<EntityLink name="target" />
from
<EntityLink name="origin" />.
<EntityLink name="Travel" />
is an `IntransitiveObject` whose
<EntityLink name="actor" />
specifies the direct object. If the
<EntityLink name="target" />
or
<EntityLink name="origin" />
are not specified, either can be determined by context.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally went home from work",
  "<EntityLink name="type" />": "Travel",
  "<EntityLink
		name="actor"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally"
  {'}'},
  "<EntityLink name="target" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Place",
    "<EntityLink name="name" />": "Home"
  {'}'},
  "<EntityLink
		name="origin"
	/>": {'{'}
    "<EntityLink name="type" />": "Place",
    "<EntityLink
		name="name"
	/>": "Work"
  {'}'}
{'}'}
			</pre>
