<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Identifies the
<EntityLink name="Object" />
or
<EntityLink name="Link" />
type. Multiple values may be specified.
