<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is undoing the
<EntityLink name="object" />. In most cases, the
<EntityLink name="object" />
will be an
<EntityLink name="Activity" />
describing some previously performed action (for instance, a person may have previously "liked" an
article but, for whatever reason, might choose to undo that like at some later point in time). The
<EntityLink name="target" />
and
<EntityLink name="origin" />
typically have no defined meaning.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally retracted her offer to John",
  "<EntityLink name="type" />": "Undo",
  "<EntityLink
		name="actor"
	/>": "http://sally.example.org",
  "<EntityLink name="object" />": {'{'}
    "<EntityLink
		name="type"
	/>": "Offer",
    "<EntityLink name="actor" />": "http://sally.example.org",
    "<EntityLink
		name="object"
	/>": "http://example.org/posts/1",
    "<EntityLink
		name="target"
	/>": "http://john.example.org"
  {'}'}
{'}'}
			</pre>
