<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
is undoing the
<EntityLink name="object" />. In most cases, the
<EntityLink name="object" />
will be an
<EntityLink name="Activity" />
describing some previously performed action (for instance, a person may have previously "liked" an
article but, for whatever reason, might choose to undo that like at some later point in time). The
<EntityLink name="target" />
and
<EntityLink name="origin" />
typically have no defined meaning.
