<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Specifies the measurement units for the
<EntityLink name="radius" />
and
<EntityLink name="altitude" />
properties on a
<EntityLink name="Place" />
object. If not specified, the default is assumed to be "m" for "meters".
