<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

Indicates that the
<EntityLink name="actor" />
has updated the
<EntityLink name="object" />. Note, however, that this vocabulary does not define a mechanism for
describing the actual set of modifications made to
<EntityLink name="object" />. The
<EntityLink name="target" />
and
<EntityLink name="origin" />
typically have no defined meaning.

<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="summary"
	/>": "Sally updated her note",
  "<EntityLink name="type" />": "Update",
  "<EntityLink
		name="actor"
	/>": {'{'}
    "<EntityLink name="type" />": "Person",
    "<EntityLink
		name="name"
	/>": "Sally"
  {'}'},
  "<EntityLink name="object" />": "http://example.org/notes/1"
{'}'}
			</pre>
