<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

The date and time at which the object was updated
<pre>
				{'{'}
  "@context": "https://www.w3.org/ns/activitystreams",
  "<EntityLink
		name="name"
	/>": "Cranberry Sauce Idea",
  "<EntityLink name="type" />": "Note",
  "<EntityLink
		name="content"
	/>": "Mush it up so it does not have the same shape as the can.",
  "<EntityLink
		name="updated"
	/>": "2014-12-12T12:12:12Z"
{'}'}
			</pre>
