<!-- generated by /src/activity_streams_notes_html.gen.ts -->
<script>
	import EntityLink from '../EntityLink.svelte';
	window.hack = EntityLink;
</script>

On a
<EntityLink name="Link" />, specifies a hint as to the rendering width in device-independent pixels
of the linked resource.
