import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {to_root_path} from '@feltcoop/gro/dist/paths.js';
import {to_embedded_json} from 'src/render.js';

// Renders the vocabulary data as a TypeScript file with type annotated JSON.

// TODO parse from raw JSON instead of inserting as JS
export const gen: Gen = async ({fs, origin_id}) => {
	const notes_data = JSON.parse(await fs.read_file('src/activity_streams_notes.json', 'utf8'));
	return `
// generated by ${to_root_path(origin_id)}
export const notes: {[key: string]: string} = ${to_embedded_json(notes_data.notes)};
  `;
};
