import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';
import {toEmbeddedJson} from './render.js';

// Renders the vocabulary data as a TypeScript file with type annotated JSON.

// TODO parse from raw JSON instead of inserting as JS

export const gen: Gen = async ({fs, originId}) => {
	const examplesData = JSON.parse(await fs.readFile('src/activity_streams_examples.json', 'utf8'));
	return `
// generated by ${toRootPath(originId)}
import type {VocabularyTerm} from './activity_streams.js';
export const examples: {[key: string]: VocabularyTerm[]} = ${toEmbeddedJson(examplesData.examples)};
  `;
};
