import {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';

import {vocabulary, VocabularyItem} from './activity_streams.js';
import {vocabularyNotes} from './activity_streams_notes.js';

// this renders a bunch of Svelte files from the notes

// TODO make this render to plain HTML as an optimization when interactivity isn't needed

const OUT_DIR = 'notes';

const toOutFile = (name: string): string => `${OUT_DIR}/${name}`;

export const gen: Gen = async ({originId}) => {
	const files = vocabulary.map((item) => {
		item.name;
		return {fileName: toOutFile(`${item.name}.svelte`), contents: toContents(item, originId)};
	});
	files.push({
		fileName: toOutFile('index.ts'),
		contents: toIndexContents(originId),
	});
	return files;
};

// TODO improve this authoring experience, maybe plain svelte files or `.gen.svelte` files or smth
const toContents = (item: VocabularyItem, originId: string): string => {
	const rendered = {
		// TODO do this for real - but it probably gets stripped just fine
		imports: `import EntityLink from '../EntityLink.svelte';window.hack=EntityLink;`,
		contents: processNotes(vocabularyNotes[item.name]),
	};
	return `
<!-- generated by /${toRootPath(originId)} -->

${
	rendered.imports?.length
		? `<script>
  ${rendered.imports}
</script>`
		: ''
}

${rendered.contents}
`;
};

const processNotes = (notes: string): string => {
	return notes.replace(/`(.+?)`/g, (text, $1) => {
		if ($1 in vocabularyNotes) {
			return `<EntityLink name="${$1}" />`;
		}
		return text;
	});
};

const toIndexContents = (originId: string): string => `
/* generated by /${toRootPath(originId)} */
${vocabulary
	.map((item) => `export {default as ${item.name}} from './${item.name}.svelte';`)
	.join('')}
`;
