import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';

// Renders the vocabulary data as a TypeScript file with type annotated JSON.

// TODO type is busted because of postprocessing, need to do that ahead of time
// to replace `addExtendedBy`

// TODO parse from raw JSON instead of inserting as JS

export const gen: Gen = async ({fs, originId}) => {
	const examplesData = JSON.parse(await fs.readFile('src/activity_streams.json', 'utf8'));
	const vocabulary = examplesData.vocabulary.map((v: any) => ({...v, notes: undefined}));
	return `
// generated by ${toRootPath(originId)}
export const vocabulary: any[] = ${JSON.stringify(vocabulary)};
  `;
};
