import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {to_root_path} from '@feltcoop/gro/dist/paths.js';

import {toEmbeddedJson} from 'src/render.js';

// Renders the vocabulary data as a TypeScript file with type annotated JSON.

// TODO parse from raw JSON instead of inserting as JS

export const gen: Gen = async ({fs, origin_id}) => {
	const examplesData = JSON.parse(await fs.read_file('src/activity_streams_examples.json', 'utf8'));
	return `
// generated by ${to_root_path(origin_id)}
import type {VocabularyTerm} from 'src/activity_streams.js';
export const examples: {[key: string]: VocabularyTerm[]} = ${toEmbeddedJson(examplesData.examples)};
  `;
};
