import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';
import {toEmbeddedJson} from './render.js';

// Renders the vocabulary data as a TypeScript file with type annotated JSON.

// TODO parse from raw JSON instead of inserting as JS
export const gen: Gen = async ({fs, originId}) => {
	const notesData = JSON.parse(await fs.readFile('src/activity_streams_notes.json', 'utf8'));
	return `
// generated by ${toRootPath(originId)}
export const notes: {[key: string]: string} = ${toEmbeddedJson(notesData.notes)};
  `;
};
